using UnityEngine; using UnityEngine.EventSystems; using UnityEngine.UI; using PhysicsMaster.Gameplay; using PhysicsMaster.Services; using PhysicsMaster.UI;
namespace PhysicsMaster.Core {
    public sealed class AppController : MonoBehaviour {
        Canvas canvas; Camera cam; DrawingController drawing; LevelData level; Text hudInk,hudTitle; float elapsed; bool completed,sandbox; GameObject world;
        void Awake(){Application.targetFrameRate=60;QualitySettings.vSyncCount=0;Screen.sleepTimeout=SleepTimeout.Never;LocalizationService.Initialize();cam=Camera.main;cam.orthographic=true;cam.orthographicSize=5;cam.backgroundColor=Theme.Background;if(EventSystem.current==null){var e=new GameObject("EventSystem");e.AddComponent<EventSystem>();e.AddComponent<StandaloneInputModule>();}canvas=UiFactory.Canvas();ShowMainMenu();}
        void Update(){if(drawing!=null&&hudInk!=null){hudInk.text=$"{LocalizationService.T("ink")} {drawing.RemainingInk:0.0}";if(drawing.SimulationRunning&&!completed)elapsed+=Time.deltaTime;}if(drawing!=null&&drawing.SimulationRunning&&!completed&&FindBall()!=null&&FindBall().transform.position.y<-6)ShowFailure();}
        void ResetScreen(){Time.timeScale=1;if(drawing)Destroy(drawing);if(world)Destroy(world);world=null;drawing=null;UiFactory.Clear(canvas.transform);}
        public void ShowMainMenu(){sandbox=false;ResetScreen();CreateLabBackdrop();UiFactory.Label(canvas.transform,"PHYSICS MASTER",new Vector2(0,620),new Vector2(900,120),72,Theme.Navy).fontStyle=FontStyle.Bold;UiFactory.Label(canvas.transform,"DRAW • TEST • SOLVE",new Vector2(0,530),new Vector2(700,70),31,Theme.Purple);UiFactory.Button(canvas.transform,LocalizationService.T("continue"),new Vector2(0,300),new Vector2(680,120),Theme.Mint,()=>StartLevel(SaveService.CurrentLevel));UiFactory.Button(canvas.transform,LocalizationService.T("levels"),new Vector2(0,140),new Vector2(680,105),Theme.Blue,ShowLevels);UiFactory.Button(canvas.transform,LocalizationService.T("sandbox"),new Vector2(0,0),new Vector2(680,105),Theme.Purple,StartSandbox);UiFactory.Button(canvas.transform,LocalizationService.T("daily"),new Vector2(0,-140),new Vector2(680,105),Theme.Gold,ClaimDaily);UiFactory.Button(canvas.transform,LocalizationService.T("shop"),new Vector2(-180,-290),new Vector2(320,90),Theme.Coral,ShowShop);UiFactory.Button(canvas.transform,"AR / EN",new Vector2(180,-290),new Vector2(320,90),Theme.Navy,()=>{LocalizationService.Toggle();ShowMainMenu();});UiFactory.Label(canvas.transform,$"★ {TotalStars()}     ● {SaveService.Coins}",new Vector2(0,-470),new Vector2(650,80),38,Theme.Navy);}
        void CreateLabBackdrop(){world=new GameObject("MenuLab");CreateCircle("DecorBall",new Vector2(-6,-3),.55f,Theme.Gold,false);CreateBox("DecorPlatform",new Vector2(-5.4f,-3.7f),new Vector2(3,.25f),Theme.Navy,false);CreateCircle("DecorMagnet",new Vector2(6,2.5f),.7f,Theme.Coral,false);}
        int TotalStars(){int n=0;for(int i=1;i<=50;i++)n+=SaveService.Stars(i);return n;}
        void ClaimDaily(){bool ok=SaveService.ClaimDaily();ShowMessage(ok?LocalizationService.T("claimed"):"COME BACK TOMORROW",ShowMainMenu);}
        void ShowMessage(string message,System.Action back){ResetScreen();UiFactory.Panel(canvas.transform,"Card",Vector2.zero,new Vector2(850,520),Theme.Panel);UiFactory.Label(canvas.transform,message,new Vector2(0,80),new Vector2(760,150),52,Theme.Navy);UiFactory.Button(canvas.transform,"OK",new Vector2(0,-110),new Vector2(350,95),Theme.Mint,()=>back());}
        void ShowShop(){ResetScreen();UiFactory.Label(canvas.transform,LocalizationService.T("shop"),new Vector2(0,700),new Vector2(800,100),65,Theme.Navy);string[] items={"NEON INK • 500 COINS","MIDNIGHT LAB • 10 GEMS","NO ADS • PLAY BILLING","HINT PACK • PLAY BILLING"};for(int i=0;i<items.Length;i++){int k=i;UiFactory.Button(canvas.transform,items[i],new Vector2(0,440-i*150),new Vector2(800,110),i<2?Theme.Purple:Theme.Blue,()=>Debug.Log("Shop item "+k));}UiFactory.Button(canvas.transform,LocalizationService.T("menu"),new Vector2(0,-550),new Vector2(500,100),Theme.Navy,ShowMainMenu);}
        public void ShowLevels(){ResetScreen();UiFactory.Label(canvas.transform,LocalizationService.T("levels"),new Vector2(0,770),new Vector2(800,100),65,Theme.Navy);for(int i=1;i<=50;i++){int id=i;int row=(i-1)/5,col=(i-1)%5;float x=-360+col*180,y=610-row*130;bool open=i<=SaveService.Unlocked;string label=open?$"{i}\n{new string('★',SaveService.Stars(i))}":"LOCK";UiFactory.Button(canvas.transform,label,new Vector2(x,y),new Vector2(145,105),open?ChapterColor((i-1)/10):new Color(.55f,.58f,.6f),()=>{if(open)StartLevel(id);});}UiFactory.Button(canvas.transform,LocalizationService.T("menu"),new Vector2(0,-760),new Vector2(460,90),Theme.Navy,ShowMainMenu);}
        Color ChapterColor(int c)=>new[]{Theme.Blue,Theme.Mint,Theme.Gold,Theme.Purple,Theme.Coral}[Mathf.Clamp(c,0,4)];
        public void StartSandbox(){sandbox=true;StartLevel(1);}
        public void StartLevel(int id){ResetScreen();completed=false;elapsed=0;level=JsonUtility.FromJson<LevelData>(Resources.Load<TextAsset>($"Levels/level_{id:000}").text);SaveService.CurrentLevel=id;Physics2D.gravity=new Vector2(0,level.reverseGravity?level.gravity:-level.gravity);world=new GameObject("World");BuildWorld();BuildHud();}
        void BuildWorld(){CreateBox("Floor",new Vector2(0,-4.55f),new Vector2(18,.45f),Theme.Navy,false);CreateBox("Shelf",new Vector2(0,-1.2f),new Vector2(3.4f,.22f),new Color32(115,140,145,255),false);var ball=CreateCircle("DynamicBall",new Vector2(level.ballX,level.ballY),.42f,Theme.Gold,true);var face=CreateCircle("BallEye",ball.transform.position+new Vector3(.12f,.08f,-.1f),.055f,Theme.Navy,false);Destroy(face.GetComponent<CircleCollider2D>());face.transform.SetParent(ball.transform);face.transform.localPosition=new Vector3(.12f,.08f,-.1f);var goal=CreateBox("Goal",new Vector2(level.goalX,level.goalY),new Vector2(1.7f,.24f),Theme.Mint,false);var trigger=goal.GetComponent<BoxCollider2D>();trigger.isTrigger=true;var zone=goal.AddComponent<GoalZone>();zone.Entered=CompleteLevel;if(level.movingObstacle)CreateBox("Obstacle",new Vector2(1.1f,.7f),new Vector2(.35f,2.2f),ChapterColor(level.chapter-1),false);if(level.hazard=="Spikes"||level.hazard=="Lava")CreateBox("Hazard",new Vector2(-.5f,-4.15f),new Vector2(3.2f,.25f),Theme.Coral,false);drawing=gameObject.AddComponent<DrawingController>();drawing.MaxInk=sandbox?999:level.inkLimit;}
        GameObject CreateBox(string n,Vector2 p,Vector2 size,Color color,bool dynamic){var g=new GameObject(n);g.transform.SetParent(world?world.transform:null);g.transform.position=p;g.transform.localScale=size;var s=g.AddComponent<SpriteRenderer>();s.sprite=WhiteSprite();s.color=color;var c=g.AddComponent<BoxCollider2D>();if(dynamic){var b=g.AddComponent<Rigidbody2D>();b.simulated=false;b.collisionDetectionMode=CollisionDetectionMode2D.Continuous;c.sharedMaterial=Material(level?.friction??.3f,level?.bounciness??.1f);}return g;}
        GameObject CreateCircle(string n,Vector2 p,float radius,Color color,bool dynamic){var g=new GameObject(n);g.transform.SetParent(world?world.transform:null);g.transform.position=p;g.transform.localScale=Vector3.one*radius*2;var s=g.AddComponent<SpriteRenderer>();s.sprite=CircleSprite();s.color=color;var c=g.AddComponent<CircleCollider2D>();if(dynamic){var b=g.AddComponent<Rigidbody2D>();b.simulated=false;b.collisionDetectionMode=CollisionDetectionMode2D.Continuous;c.sharedMaterial=Material(level?.friction??.3f,level?.bounciness??.1f);}return g;}
        PhysicsMaterial2D Material(float f,float b){var m=new PhysicsMaterial2D("LevelMaterial");m.friction=f;m.bounciness=b;return m;}
        Sprite WhiteSprite(){var t=Texture2D.whiteTexture;return Sprite.Create(t,new Rect(0,0,t.width,t.height),new Vector2(.5f,.5f),1);}
        Sprite CircleSprite(){const int n=64;var t=new Texture2D(n,n,TextureFormat.RGBA32,false);var px=new Color[n*n];for(int y=0;y<n;y++)for(int x=0;x<n;x++){float dx=x-n/2f,dy=y-n/2f;px[y*n+x]=dx*dx+dy*dy<(n*.48f)*(n*.48f)?Color.white:Color.clear;}t.SetPixels(px);t.Apply();return Sprite.Create(t,new Rect(0,0,n,n),new Vector2(.5f,.5f),n);}
        void BuildHud(){UiFactory.Panel(canvas.transform,"Top",new Vector2(0,810),new Vector2(1040,190),new Color32(255,255,255,236));hudTitle=UiFactory.Label(canvas.transform,sandbox?LocalizationService.T("sandboxInfo"):$"{level.id} • {LocalizationService.T("objective")}",new Vector2(0,850),new Vector2(780,75),35,Theme.Navy);hudInk=UiFactory.Label(canvas.transform,"",new Vector2(-390,770),new Vector2(230,65),30,Theme.Purple);UiFactory.Button(canvas.transform,LocalizationService.T("hint"),new Vector2(390,770),new Vector2(210,70),Theme.Gold,Hint);var bar=UiFactory.Panel(canvas.transform,"ToolBar",new Vector2(0,-800),new Vector2(1050,250),new Color32(255,255,255,243));string[] names={"FREE","LINE","CIRCLE","BOX","PIN"};for(int i=0;i<5;i++){int k=i;UiFactory.Button(bar.transform,names[i],new Vector2(-390+i*195,55),new Vector2(175,70),k==0?Theme.Blue:Theme.Purple,()=>drawing.Tool=(DrawingTool)k);}UiFactory.Button(bar.transform,LocalizationService.T("undo"),new Vector2(-330,-55),new Vector2(190,70),Theme.Navy,()=>drawing.Undo());UiFactory.Button(bar.transform,LocalizationService.T("clear"),new Vector2(-110,-55),new Vector2(190,70),Theme.Coral,()=>drawing.Clear());UiFactory.Button(bar.transform,LocalizationService.T("play"),new Vector2(185,-55),new Vector2(330,80),Theme.Mint,()=>drawing.StartSimulation());UiFactory.Button(bar.transform,"☰",new Vector2(430,-55),new Vector2(120,75),Theme.Navy,Pause);}
        void Hint(){ShowOverlay("DRAW A RAMP OR BRIDGE\nارسم منحدراً أو جسراً",()=>{});}
        void Pause(){Time.timeScale=0;ShowOverlay(LocalizationService.T("pause"),()=>Time.timeScale=1,true);}
        void ShowOverlay(string title,System.Action close,bool pause=false){var panel=UiFactory.Panel(canvas.transform,"Overlay",Vector2.zero,new Vector2(850,650),new Color32(255,255,255,250));UiFactory.Label(panel.transform,title,new Vector2(0,170),new Vector2(730,180),48,Theme.Navy);UiFactory.Button(panel.transform,LocalizationService.T("resume"),new Vector2(0,20),new Vector2(520,90),Theme.Mint,()=>{if(pause)Time.timeScale=1;Destroy(panel);close();});UiFactory.Button(panel.transform,LocalizationService.T("restart"),new Vector2(0,-100),new Vector2(520,90),Theme.Blue,()=>StartLevel(level.id));UiFactory.Button(panel.transform,LocalizationService.T("menu"),new Vector2(0,-220),new Vector2(520,90),Theme.Navy,ShowMainMenu);}
        void CompleteLevel(){if(completed)return;completed=true;int stars=sandbox?0:1+(elapsed<level.timeLimit?1:0)+(drawing.StrokeCount<=level.parStrokes?1:0);if(!sandbox)SaveService.Complete(level.id,stars);Effects.Burst(new Vector2(level.goalX,level.goalY),Theme.Gold,24);var p=UiFactory.Panel(canvas.transform,"Result",Vector2.zero,new Vector2(880,720),new Color32(255,255,255,250));UiFactory.Label(p.transform,LocalizationService.T("solved"),new Vector2(0,230),new Vector2(760,100),52,Theme.Navy);UiFactory.Label(p.transform,new string('★',stars),new Vector2(0,110),new Vector2(650,100),76,Theme.Gold);UiFactory.Label(p.transform,$"{elapsed:0.0}s   •   {drawing.StrokeCount} strokes",new Vector2(0,20),new Vector2(650,70),30,Theme.Purple);UiFactory.Button(p.transform,LocalizationService.T("next"),new Vector2(0,-100),new Vector2(560,90),Theme.Mint,()=>StartLevel(Mathf.Min(50,level.id+1)));UiFactory.Button(p.transform,LocalizationService.T("retry"),new Vector2(0,-215),new Vector2(560,85),Theme.Blue,()=>StartLevel(level.id));UiFactory.Button(p.transform,LocalizationService.T("menu"),new Vector2(0,-320),new Vector2(560,80),Theme.Navy,ShowMainMenu);}
        void ShowFailure(){if(completed)return;completed=true;ShowOverlay("TRY A DIFFERENT SHAPE\nجرّب شكلاً مختلفاً",()=>{});}
        GameObject FindBall()=>GameObject.Find("DynamicBall");
    }
}
